name: Build & Deploy Frontend

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build_and_push:
    name: Build & Push Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASS }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            prithuanan/teamsync-social-flow:latest
            prithuanan/teamsync-social-flow:${{ github.sha }}

  deploy:
    name: Deploy to Azure VM
    needs: build_and_push
    runs-on: ubuntu-latest

    steps:
      - name: SSH & Deploy
        uses: appleboy/ssh-action@v1.1.0
        with:
          host:     ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key:      ${{ secrets.SSH_KEY }}
          port:     22
          script: |
            set -eux

            # Tell Docker which tag to use
            export TAG=${{ github.sha }}

            # Pull the image for this commit, or fallback to latest
            docker pull prithuanan/teamsync-social-flow:${TAG} || \
              docker pull prithuanan/teamsync-social-flow:latest

            # Replace the running container
            docker rm -f frontend || true
            docker run -d \
              --name frontend \
              -p 3000:80 \
              prithuanan/teamsync-social-flow:${TAG}

